// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtzIW6bXCFWwI4twZi_rW5MYvYjTjt6rE',
    appId: '1:427415408925:web:8b17970a8ad9212ab391f4',
    messagingSenderId: '427415408925',
    projectId: 'chat-app-26f9a',
    authDomain: 'chat-app-26f9a.firebaseapp.com',
    storageBucket: 'chat-app-26f9a.appspot.com',
    measurementId: 'G-HW7225Q8WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHOIATHMTSKQhxMZCnGVwznP3knhCmUo8',
    appId: '1:427415408925:android:d76f6aba1eb9921bb391f4',
    messagingSenderId: '427415408925',
    projectId: 'chat-app-26f9a',
    storageBucket: 'chat-app-26f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGEzY72zSfbJ5PY9KNhi6GolMB_92z1Q',
    appId: '1:427415408925:ios:8d611120af5e3113b391f4',
    messagingSenderId: '427415408925',
    projectId: 'chat-app-26f9a',
    storageBucket: 'chat-app-26f9a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkGEzY72zSfbJ5PY9KNhi6GolMB_92z1Q',
    appId: '1:427415408925:ios:8d611120af5e3113b391f4',
    messagingSenderId: '427415408925',
    projectId: 'chat-app-26f9a',
    storageBucket: 'chat-app-26f9a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtzIW6bXCFWwI4twZi_rW5MYvYjTjt6rE',
    appId: '1:427415408925:web:2bc4446edc2db5e7b391f4',
    messagingSenderId: '427415408925',
    projectId: 'chat-app-26f9a',
    authDomain: 'chat-app-26f9a.firebaseapp.com',
    storageBucket: 'chat-app-26f9a.appspot.com',
    measurementId: 'G-PTXDNYBG7W',
  );
}
